# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Ringsterz Log # 블로그 제목
tagline:             'Log for everything' # 페이지 제목 옆에 나타나는 설명 글
description:         '궁금한 것, 배운 것, 알게된 것 등을 정리하기 위한 블로그입니다.' # 사이드바 상단에 나타나는 블로그 설명
url:                 https://minyoungjung.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Minyoung Jung
  url:               https://MinyoungJung.github.io
  email:             minyoungjung84@gmail.com

# Custom vars
version:             1.0.0

# Pagination
gems: [jekyll-paginate]
paginate_path: "page:num"
